name: Build Nginx Images

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - nginx-build

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-nginx-images
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  debian:
    name: Build Debian NGINX container image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: nginxinc/docker-nginx
          path: docker-nginx
          token: ${{ secrets.NGINX_PAT }}
          ref: 'master'

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          platforms: arm,arm64,ppc64le,s390x

      - name: Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Extract NGINX version
        id: nginx-version
        run: |
          version=$(egrep "^ENV NGINX_VERSION" docker-nginx/mainline/debian/Dockerfile  | awk '{ print $3 }')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            name=nginx/nginx
          tags: |
            type=raw,value=${{ steps.nginx-version.outputs.version }}

      - name: Build NGINX Container
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          file: Dockerfile
          context: "docker-nginx/mainline/debian"
          cache-from: type=gha,scope=nginx-debian
          cache-to: type=gha,scope=nginx-debian,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          platforms: "linux/arm, linux/arm64, linux/amd64, linux/ppc64le, linux/s390x"
          pull: true
          push: false
          load: true
