name: Publish GCP Marketplace Bundles

on:
  push:
    branches:
      - main
      - release-*
      - gcp-publish

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-gcp-publish
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  checks:
    name: Checks and variables
    runs-on: ubuntu-22.04
    outputs:
      chart_version: ${{ steps.vars.outputs.chart_version }}
      ic_version: ${{ steps.vars.outputs.ic_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: refs/heads/release-3.5

      - name: Output Variables
        id: vars
        run: |
          source .github/data/version.txt
          echo "ic_version=${IC_VERSION}" >> $GITHUB_OUTPUT
          echo "chart_version=${HELM_CHART_VERSION}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  gcp-marketplace:
    name: Trigger PR for GCP Marketplace
    runs-on: ubuntu-22.04
    needs: [checks]
    steps:
      - name:
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.NGINX_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'kubernetes-ingress-gcp',
              workflow_id: 'sync-chart.yml',
              ref: 'main',
              inputs: {
              chart_version: '${{ needs.checks.outputs.chart_version }}'
              },
            })
