name: Test Self Hosted Runner

on:
  push:
    branches:
      - new-runner-test

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-self-hosted-runner
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  list-tags:
    name: List tags
    permissions:
      contents: read # for docker/build-push-action to read repo content
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      id-token: write # for OIDC login to AWS
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Id Token
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: idtoken
        with:
          script: |
            let id_token = await core.getIDToken()
            core.setOutput('id_token', id_token)

      - name: Login to NGINX Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker-mgmt.nginx.com
          username: ${{ steps.idtoken.outputs.id_token }}
          password: ${{ github.actor }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@a6e2e39c0a0331da29f7fd2c2a20a427e8d3ad1f # v2.1.1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Output Runner
        run: |
          echo ${{ runner.name }}/${{ runner.os }}/${{ runner.arch }}

      - name: List tags from docker-mgmt registry
        run: |
          skopeo list-tags docker://docker-mgmt.nginx.com/nginx-ic/nginx-plus-ingress

      - name: Test push to docker-mgmt registry
        run: |
          skopeo copy --retry-times 5 -a docker://gcr.io/f5-gcs-7899-ptg-ingrss-ctlr/dev/nginx-ic/nginx-plus-ingress:edge docker://docker-mgmt.nginx.com/nginx-ic/nginx-plus-ingress:edge
